# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f82e86348a2c63d1e9c42235abbb68eb"
name = "learning-purpose-app"
handle = "learning-purpose-app"
application_url = "https://andreas-trade-appeals-optional.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-07987cf7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://andreas-trade-appeals-optional.trycloudflare.com/auth/callback",
  "https://andreas-trade-appeals-optional.trycloudflare.com/auth/shopify/callback",
  "https://andreas-trade-appeals-optional.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
